### ISSUE TITLE
Dominant block functionality

### ISSUE THREAD

**Issue by alphapapa** [daniel-goossens/chisels_and_bits_2#1]
Hi,

Thanks very much for picking up this mod!

Quick question:

> Internally the chiseled block is different, instead of there being different blocks for each material (rock, cloth, etc.) the chiseled block will mimic most of the functionality of the dominant block.

In the old mod version, I did things like making lava lamps and glowstone lamps by placing individual lava/glowstone bits and building other materials around them.  It was really cool, because the more illuminated bits, the brighter the lamp.

For example, in this picture you can see a Victorian-style street lamp that works:

![k5EAYuZ](https://user-images.githubusercontent.com/601365/62955405-9f8c9980-bdb6-11e9-8179-031099c77e9a.png)

Here are a variety of lamps, some of which have the glowstone concealed, like paper lanterns.  Some of them use molten metal from...whatever mod has the forges and furnaces, etc. (haven't played for a while).

![2017-12-20_14 48 50](https://user-images.githubusercontent.com/601365/62955536-d82c7300-bdb6-11e9-8db2-05fdaa30bf76.png)

Here are two that look like table lamps, but they actually work because of the glowstone:

![2017-12-18_02 56 24](https://user-images.githubusercontent.com/601365/62955596-eed2ca00-bdb6-11e9-88c2-3c679b242cc2.png)

Will that still work?  It would be a shame if that feature was lost.

Thanks.

**Comment by daniel-goossens** [comment]
I've made special note of this to remind myself to re-add this when I get around to it. So yes, it'll be in C&B2 too.

**Comment by alphapapa** [comment]
Great, thank you.
